# Generated by Django 3.2.3 on 2021-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_todolist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
